package com.gradlesfault.sidsrx;

import java.util.ArrayList;
import java.util.prefs.PreferenceChangeEvent;

/**
 * Created by Sziraqui on 25-03-2017.
 */

public class Doctor {
    private int ID;
    private int hospitalID;
    private String name;
    private ArrayList<Prescription> prescriptions;

    Doctor(int ID, String name, int hospitalID){
        this.ID = ID;
        this.name = name;
        this.hospitalID = hospitalID;
    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public int getHospitalID() {
        return hospitalID;
    }

    public void setHospitalID(int hospitalID) {
        this.hospitalID = hospitalID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int createPrescription(int patientID){
        int presID;
        //todo : generate a unique presID
        presID = 0; // set it to value generated by id generator above;
        Prescription prescription = new Prescription(presID,this.ID,patientID);
        //todo upload prescription to remote database
        //todo check if operation was successful
        return presID;
    }
    public boolean renewPrescription(int presID){
        boolean success = false;
        Prescription prescription = Prescription.getPrescriptionById(presID);
        if(prescription.isEXPIRED()){
            //todo : set EXPIRED to false and update database
        }
        return success;
    }
}
